### ISSUE TITLE
QA for v1.0.0

### ISSUE THREAD

**Issue by blukat29** [kaiachain/kaia#1]
- Regular tests
  - [x] ok @yoomee1313 https://github.com/kaiachain/kaia/issues/1#issuecomment-2134215942
- Kaia hardfork tests
  - [x] KIP-160 RebalanceV2 test on private chain @ian0371 
    - Test system.RebalanceTreasury routine at hardfork
    - Submit memo and see getTotalSupply works
  - [x] KIP-162 Priority Fee tx processing @hyeonLewis https://github.com/kaiachain/kaia/issues/1#issuecomment-2132592918
    - Test various tx types (type 0, 2, 0xa)
    - Test various gas price fields (gasPrice, maxFeePerGas, maxPriorityFeePerGas, with respect to baseFeePerGas)
    - Validate results (proposer&sender balance changes, getTransactionReceipt, getRewards APIs, block tx ordering)
  - [x] KIP-162 Priority Fee GASPRICE opcode @hyeonLewis https://github.com/kaiachain/kaia/issues/1#issuecomment-2132592918
  - [x] KIP-163 Public Delegation and 1-block staking interval @ian0371 
    - getCommittee reacts quickly after a validator staking amount falls below / goes above minStaking
  - [x] Ending credit @yoomee1313 https://github.com/kaiachain/kaia/issues/1#issuecomment-2134262770
    - The result is retrievable via console and curl 
- RPC API changes
  - [x] KIP-162 Priority Fee related APIs @hyeonLewis https://github.com/kaiachain/kaia/issues/1#issuecomment-2132833607
    - Test various fork levels (before EthTxType, after EthTxType, after Magma, after Kaia)
    - eth_sendTransaction (txPool.add inside) reject conditions
    - eth_gasPrice
    - eth_maxPriorityFeePerGas
    - eth_feeHistory
    - Use with MetaMask (https://support.metamask.io/transactions-and-gas/gas-fees/how-to-customize-gas-settings)    
  - [x] getTotalSupply @blukat29 https://github.com/kaiachain/kaia/issues/1#issuecomment-2146761683
    - Compare mainnet result against other data sources
  - [x] Query KIP113, KIP149 contracts @blukat29 https://github.com/kaiachain/kaia/issues/1#issuecomment-2145496641
  - [x] Namespace alias @blukat29 https://github.com/kaiachain/kaia/issues/1#issuecomment-2145496641
    - `kaia` and `klay` namespaces both work via console and curl

**Comment by blukat29** [comment]
Hello @cshintov, For the v1.0.0 you can simply replace the kcn,kpn,ken binaries. The scripts kXnd and config file templates kXnd.conf shpuld work unchqnged.
But for completeness and ease of management, we are going to distribute v1.0.1 tarball, rpm and docker images. Note that the mainnet hardfork is going to be activated by v1.0.1, so 1.0.1 is actually important release.
