### ISSUE TITLE
QA for v1.0.1

### ISSUE THREAD

**Issue by blukat29** [kaiachain/kaia#14]
- [x] Regular tests except sync test and load test @yoomee1313 
  - [x] ok
- [x] The Go RPC client supports type-2 transactions [#29](https://github.com/kaiachain/kaia/pull/29) [#36](https://github.com/kaiachain/kaia/pull/36) @yoomee1313 https://github.com/kaiachain/kaia/issues/14#issuecomment-2206102388
  - [x] From a fresh Go project, `go get github.com/kaiachain/kaia` works.
  - [x] `Client` can send type-2 transactions with custom gas price & tip
- [x] RPC changes
  - [x] suggested gas price and tip is reasonable [#28](https://github.com/kaiachain/kaia/pull/28) @blukat29 https://github.com/kaiachain/kaia/issues/14#issuecomment-2206052406
  - [x] kaia_getTransaction returns correct gasPrice for mined transactions [#26](https://github.com/kaiachain/kaia/pull/26) @ian0371 https://github.com/kaiachain/kaia/issues/14#issuecomment-2203655312
  - [x] kaia_getTotalSupply returns all fields for Kairos testnet [#23](https://github.com/kaiachain/kaia/pull/23) @ian0371 https://github.com/kaiachain/kaia/issues/14#issuecomment-2203655312
  - [x] Message signing RPCs are EIP-191 compliant @ian0371 [#33](https://github.com/kaiachain/kaia/pull/33) https://github.com/kaiachain/kaia/issues/14#issuecomment-2203655312
  - [x] `kscn` can successfully query the main chain's data via `subbridge_parentOperatorBalance` [#27](https://github.com/kaiachain/kaia/pull/27) @hyunsooda 
- [x] CallTracer (formerly InternalTxTracer) changes   @blukat29 
  - [x] API `debug.trace*` output is correct [#15](https://github.com/kaiachain/kaia/pull/15)
  - [x] ChainDataFetcher InternalTrace output is correct [#16](https://github.com/kaiachain/kaia/pull/16) [#47](https://github.com/kaiachain/kaia/pull/47)
  - [x] State regen in full mode nodes [#43](https://github.com/kaiachain/kaia/pull/43)
- [x] CI packaging pipeline [#37](https://github.com/kaiachain/kaia/pull/37) @blukat29 https://github.com/kaiachain/kaia/issues/14#issuecomment-2206109054
  - [x] rc.1 rpm packages are available under packages.kaia.io
  - [x] rc.1 tgz packages are available under packages.kaia.io
- [x] Istanbul snapshot regeneration [#46](https://github.com/kaiachain/kaia/pull/48) @blukat29  https://github.com/kaiachain/kaia/issues/14#issuecomment-2227379714
  - [x] no 'failed to update kaia stakingInfo' error during node startup
  - [x] staking info related APIs for historic blocks
  - [x] chaindatafetcher blockgroup topic

Sign-Off PR: #40

**Comment by blukat29** [comment]
Message signing RPCs are EIP-191 compliant

1. Sample data

- account private key: `0x6397f5bfcef382017268d21294aed3b82d479b67323f94f7065d92a43643f20f` 
- account address: `0xbC7d1aBe33E6EC19cA873A3042A4DCF49149BC7A`
- message `0x61626364`
- signature created by MetaMask's `personal_sign` (EIP-191)
  ```js
  window.ethereum.request({ method: "eth_requestAccounts" })
  window.ethereum.request({ method: "personal_sign", params: ["0x61626364", "0xbC7d1aBe33E6EC19cA873A3042A4DCF49149BC7A"] }).then(console.log)
  0xe67ddbb12ad7c85a28b082bb3f159e637229454d34824bd96c0df38e49bf92d42167ffba7565855585de0c32407b0622b0b66fdfe7bd6566d4a19ca40b39ec631b
  ```
- signature created by Kaikas's `eth_sign` (KIP-97)
  ```js
  window.klaytn.request({ method: "eth_requestAccounts" })
  window.klaytn.request({ method: "eth_sign", params: ["0xbC7d1aBe33E6EC19cA873A3042A4DCF49149BC7A", "0x61626364"] }).then(console.log)
  0x90824271750d7a09f90a76b6f8ec1e5e2afd31790fea9f43e26c120fef3152be46ad09c76f87bd6c495859fa37127754f1f0780180df53eda80034dac036b8d31b
  ```

2. `personal_ecrecover` is EIP-191

3. `kaia_recoverFromMessage` accepts both EIP-191 and KIP-191

4. `personal_sign`, `eth_sign`, `kaia_sign` are EIP-191

**Comment by blukat29** [comment]
gasPrice and maxPriorityFeePerGas APIs

1. Monitor two nodes on Kairos: one v1.0.0, another v1.0.1
```js
setInterval(() => console.log(
  eth.blockNumber,
  eth.gasPrice/1e9,
  eth.maxPriorityFeePerGas/1e9,
  eth.feeHistory(20, 'latest', [60]).reward.flat().map((n) => parseInt(n)/1e9),
  eth.feeHistory(20, 'latest').baseFeePerGas.map((n) => parseInt(n)/1e9)
), 1000)  
```

2. Intentionally create high-tip transactions and compare the results

3. Intentionally create high-gas-fee transactions to increase the basefee and compare the results

**Comment by blukat29** [comment]
### The Go RPC client supports type-2 transactions

1. Setup node

```
> personal.importRawKey(..fresh private key..)
> personal.unlockAccount(...)
```

2. Write Go client software

```
go get -x github.com/kaiachain/kaia/client@v1.0.1-rc.1
```

```go
package main

import (
	"context"
	"fmt"

	"github.com/kaiachain/kaia/client"
)

func main() {
	c, err := client.Dial("http://my-kairos-node:8551")
	if err != nil {
		t.Fatal(err)
	}

	gP, err := c.SuggestGasPrice(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println("cid", gP.String())

	// Send unsigned transaction with type 2
}
```

**Comment by blukat29** [comment]
### CI packaging pipeline

1. rpm package

```sh
wget https://packages.kaia.io/kaia/...
yum -qlp ...rpm
sudo yum install ....rpm

ken version
sudo /etc/init.d/kend start
ken attach /var/kend/data/klay.ipc
kaia.clientVersion
kaia.blockNumber
```

2. tgz package

```sh
wget https://packages.kaia.io/kaia/...
tar xf ....tar.gz
tree ...

.../bin/ken version
sudo .../bin/kend start
ken attach /var/kend/data/klay.ipc
kaia.clientVersion
kaia.blockNumber
```

**Comment by hyunsooda** [comment]
[kscn can successfully query the main chain's data via subbridge_parentOperatorBalance https://github.com/kaiachain/kaia/pull/27 @hyunsooda]

v1.0.0:
```
> subbridge.parentOperatorBalance
Error: the method klay_getBalance does not exist/is not available
        at web3.js:6810:9(39)
        at get (web3.js:6710:66(14))
        at <eval>:1:11(1)
```

v1.0.1-rc.1:
```
> subbridge.parentOperatorBalance
6.25e+48
```

**Comment by blukat29** [comment]
## debug trace RPCs

### Check debug_trace RPCs

CallTrace formats (see #15)
- gasLimit [0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2](https://baobab.klaytnfinder.io/tx/0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2)
- revertReason [0x49aa6074a3b4970399ef2af12b109c4cb4a65ab8a833d1540e4cefa657a3c0c7](https://baobab.klaytnfinder.io/tx/0x49aa6074a3b4970399ef2af12b109c4cb4a65ab8a833d1540e4cefa657a3c0c7?tabId=internalTx)
- DelegateCall [0x931c5af31bfb906fc20effa0f90f1a8e66edefac9879729fedd18a65d64a11be](https://baobab.klaytnfinder.io/tx/0x931c5af31bfb906fc20effa0f90f1a8e66edefac9879729fedd18a65d64a11be?tabId=internalTx)
- Precompiles [0xb71df5a6628cd2c193c5155c4dabbd45604a6207334c793b512293e165a04526](https://baobab.klaytnfinder.io/tx/0xb71df5a6628cd2c193c5155c4dabbd45604a6207334c793b512293e165a04526?tabId=internalTx)
- Error codes [0xdf06945964fb2f966c89716bb936da523964c73ee30c0f556baaad90263facfd](https://baobab.klaytnfinder.io/tx/0xdf06945964fb2f966c89716bb936da523964c73ee30c0f556baaad90263facfd?tabId=internalTx)
- AccountUpdate [0xac43859eb4064916e8be8e74645d6019cc48cb6791f68ea21d42ead6bba569b5](https://baobab.klaytnfinder.io/tx/0xac43859eb4064916e8be8e74645d6019cc48cb6791f68ea21d42ead6bba569b5)
```js
conf={tracer: 'callTracer'}
debug.traceTransaction('0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2', conf)
debug.traceTransaction('0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2', conf)
debug.traceTransaction('0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2', conf)
debug.traceTransaction('0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2', conf)
debug.traceTransaction('0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2', conf)
debug.traceTransaction('0xf3b71a6f97667dba14aef6d512c9bb01c7af43756e464c57e12b2fdfa7a9d3f2', conf)

```

State regeneration
- StateRegen [0x3b0fa88a91ac18b91e0aae17fb85a7d78aad92ffed66803ec7e3b10d3d217878](https://baobab.klaytnscope.com/tx/0x3b0fa88a91ac18b91e0aae17fb85a7d78aad92ffed66803ec7e3b10d3d217878?tabId=internalTx)
  - This transaction depends on the balance of a validator reward address (0x5bb2b2977a29ad85994f601f45802f514bb5e2a1). Historical state regeneration has to be correct for the traces to be correct.
```js
// Test
txid='0x3b0fa88a91ac18b91e0aae17fb85a7d78aad92ffed66803ec7e3b10d3d217878'
block=157805568
idx = 0
conf={tracer: 'callTracer'}
T = debug.traceTransaction(txid, conf).calls[0].value
B = debug.traceBlockByNumber(block, conf)[idx].result.calls[0].value
R = debug.traceBlockByNumberRange(block, block, conf)[block].traces[idx].result.calls[0].value

// Correct value
to = '0x97d88c37e7086decc0a207426fbc38bc9c6e5e3e'
kaia.getAccount(to, block).account.balance
"0xc83bc715f06e921dfa"
kaia.getAccount(to, block-1).account.balance
"0xc678ada73997e4ce4c"
>>> v = 0xc83bc715f06e921dfa - 0xc678ada73997e4ce4c
>>> v, hex(v)
(32505133517088051118, '0x1c3196eb6d6ad4fae')
```

**Comment by blukat29** [comment]
## istanbul snapshot regeneration

- [ ] no 'failed to update kaia stakingInfo' error during node startup

<details><summary>v1.0.1-rc.2 - ERROR messages from the last multiple of 1024 to current block</summary>

```
kend restart

INFO[07/14,14:44:09 Z] [5] Loaded most recent local header           number=159386816 hash=61ecf4…10fc59 td=159386817 age=7s99ms
INFO[07/14,14:44:09 Z] [5] Loaded most recent local full block       number=159386816 hash=61ecf4…10fc59 td=159386817 age=7s99ms
INFO[07/14,14:44:09 Z] [5] Loaded most recent local fast block       number=159386816 hash=61ecf4…10fc59 td=159386817 age=7s99ms
INFO[07/14,14:44:09 Z] [5] prefetchTxWorkers are started             num=32
INFO[07/14,14:44:09 Z] [41] Live pruning is disabled because flag not stored in database
INFO[07/14,14:44:09 Z] [5] InitDeriveSha                             initial=0 withGov=true
INFO[07/14,14:44:09 Z] [5] Loaded local transaction journal          transactions=0 dropped=0
INFO[07/14,14:44:09 Z] [5] Regenerated local transaction journal     transactions=0 accounts=0
ERROR[07/14,14:44:09 Z] [44] failed to update kaia stakingInfo         block number=159386625 err="failed to get state at number 159386625. root err: missing trie node 1e7248fae3d7fd0aad75c5c0d566ce28bf8fd4addb215a1a94fcdf3ab696b07b (path )"
ERROR[07/14,14:44:09 Z] [44] failed to update kaia stakingInfo         block number=159386626 err="failed to get state at number 159386626. root err: missing trie node 91c427030d7c3dcb61d69f2595e5da292fe57c16dabea6b847e79e875c3ff92a (path )"
...
ERROR[07/14,14:44:09 Z] [44] failed to update kaia stakingInfo         block number=159386814 err="failed to get state at number 159386814. root err: missing trie node ad6ada614fdbd7daeb3ccee99dd7f6a6bd758caf40a2db30f5cf556d233fb930 (path )"
ERROR[07/14,14:44:09 Z] [44] failed to update kaia stakingInfo         block number=159386815 err="failed to get state at number 159386815. root err: missing trie node f93cdecd7b9fb5001f3db5bdd97d6161bd301fcd8a16a78ce516416dfe962d5b (path )"
INFO[07/14,14:44:09 Z] [40] Starting P2P networking
...
INFO[07/14,14:44:39 Z] [28] Downloader queue stats                    receiptTasks=0 blockTasks=0 stakingInfoTasks=0 itemSize=744.90B throttle=8192
INFO[07/14,14:44:39 Z] [5] Inserted a new block                      number=159386817 hash=5d860d…e8bd7d txs=0 gas=0 elapsed=50.456ms  processTxs=176ns finalize=6.710ms validateState=608.51µs totalWrite=1.587822ms trieWrite=991.401µs
```
</details> 

<details><summary>v1.0.1-rc.3</summary>
<p>



</p>
</details> 

- [ ] staking info related APIs for historic blocks

Outputs must be equal between archive and full nodes:

- Governance module
  - [ ] `kaia_getStakingInfo`
  - [ ] `kaia_getRewards`
  - [ ] `kaia_getRewardsAccumulated`
  - Note that `kaia_getTotalSupply` is unaffected because it's unrelated to staking info ([src](https://github.com/kaiachain/kaia/blob/v1.0.1-rc.2/reward/reward_distributor.go#L239))
- Istanbul module
  - [ ] `kaia_getCommitee`
  - [ ] `kaia_getCouncil`
  - [ ] `kaia_getBlockWithConsensusInfoByNumber`
- Chaindatafetcher module
  - [ ] the ConsensusInfo in the kafka blockgroup message
