### ISSUE TITLE
Add Ethereum compatibility test

### ISSUE THREAD

**Issue by ulbqb** [kaiachain/kaia#152]
## Problem

Kaia isn't tested about Ethereum compatibility.

## Solution

Kaia can be tested using ethereum/tests` and `ethereum/execution-spec-test` with some modification.

## Todo

- [x] Add stateTest from `ethereum/execution-spec-test`
  - [x] Prague
    - [x] except 7702: #154
    - [x] 7702: #172
  - [x] Cancun: #154
  - [x] Shanghai: #129
  - [x] Berlin - Frontier: #164
- [x] Investigating the difference between blockchainTest & stateTest: https://github.com/kaiachain/kaia/issues/152#issuecomment-2530402638
- [x] Add blockchainTests from `ethereum/execution-spec-test`
  - [x] post state test: #238
  - [ ] other tests
- [x] Investigating the difference between `ethereum/tests` & `ethereum/execution-spec-test`: https://github.com/kaiachain/kaia/issues/152#issuecomment-2720118377
- [x] ~~Add tests using `ethereum/tests` if it's needed~~
- [ ] Add the detail to README #241

sub tasks:

- [x] Replace execution-spec-test file with latest major version #245
- [x] too many isTestExecutionSpecState branches, separate test runner like Run and runLegacy
- [ ] move useEth functions to eest_utils.go
- [x] share the difference processing between state and block, and use the useEth function for all
- [ ] enable CancunToPragueAtTime15k on block tests
- [ ] gaslimit issue

**Comment by ulbqb** [comment]
# Investigating the difference between blockchainTest & stateTest

TBU

**Comment by Mdaiki0730** [comment]
I will report the problem I encountered when running ETH blockchain testing on kaia.

## Blockchain test flow
1. Calculate genesis from json
2. Compare the genesis block hash and state root with the expected in json
3. Create a Kaia blockchain object and insert a json block RLP into it.
4. After inserting the block, compare the expected state (post state) in the JSON with the actual state.
5. Validate the header of the inserted block

## How adopt kaia
There are two solutions to this problem.
**1. prepare following components**
- A converter that converts `blocks fields` to Kaia blocks
  - A component that replicates the kaia state root
  - A component that calculates the Kaia header from the ETH header.
- A converter that converts Kaia blocks to eth blocks
  - A component that replicates the eth state root (can we use state_test?)
  - A component that calculates the eth header from the kaia header.
This would require not only a converter before comparison, but also something like a mock chain to prepare the data to be inserted. Maintenance would also be costly.

**2. compare only state**
- Ignore the header and block only the txs to verify the state.
- There is an experiment in my fork repository.
  - https://github.com/Mdaiki0730/kaia/commit/c6ae4c9c55965a9834f445275ee770d010f2bdad

**Comment by Mdaiki0730** [comment]
> Basically, they all are the scenario where something is executed as another tx after code is set in the same block. In the StateTest, the state of first tx can be created using the pre state but this isn’t that the state is created during executing the same block. Considering this perspective, they are different and they are testing the continuous state transition in the same block.

In my opinion, option 2 is the better option.
The reason is that it can achieve the purpose of blockchain testing presented by Shogo and requires only minor modifications.

Option 1 is expected to require a large amount of code to be added for the block converter. It may be necessary to use something like a mock chain to create the desired data using data obtained from JSON data.
Also, the purpose of checking what compatibility is being checked is unclear.

Could you give me your opinion? @kaiachain/core @shiki-tak @tnasu @ulbqb @da1suk8

**Comment by ulbqb** [comment]
@Mdaiki0730 
I agree with you. The comparison of the post state is essential. I don't know whether or not other comparisons are needed now but I think you can start with option 2.

**Comment by shiki-tak** [comment]
@Mdaiki0730 
I tried option 1, but I ended up having to write the same code as option 2 to validate the PostState.
And if you need to prepare data for Kaia to validate the header, validating the value doesn't seem to make much sense.

**Comment by Mdaiki0730** [comment]
@kaiachain/core 
In the first place, what does the core team think about conducting blockchainTests?
I agree with Shogo's comment. It means doing blockchainTests.
https://github.com/kaiachain/kaia/issues/152#issuecomment-2530402638

**Comment by blukat29** [comment]
Yes running blockchainTests should increase the test coverage. Also option 2 sounds like the only viable option. It's indeed meaningless to compare the Kaia's block against Eth's as their state roots and block hashes are different..

**Comment by Mdaiki0730** [comment]
Thank you all for giving your opinions. I'll create a pull request for option 2.
Since there are problems with precompile range for that as well, I'll create a separate issue.

**Comment by ulbqb** [comment]
New version, [pectra-devnet-5](https://github.com/ethereum/execution-spec-tests/releases/tag/pectra-devnet-5%40v1.0.0) became available. We can remove [this process](https://github.com/kaiachain/kaia/blob/9741b5f808d47d105d2768f52ac96c1e1ee18ac7/build/ci.go#L278) because this looks to contain EIPs for all forks.

**Comment by Mdaiki0730** [comment]
Regarding as `Add stateTest from ethereum/execution-spec-test for old EIPs`, it seems like old forks are skiped now at [these lines](https://github.com/kaiachain/kaia/blob/dev/tests/state_test.go#L113-L123).
We need to check again it.

**Comment by ulbqb** [comment]
@Mdaiki0730 
The lines means it stops running Kaia as old forks. That doesn't mean it stops executing old EIP tests.

**Comment by Mdaiki0730** [comment]
Ah, I seem to have misunderstood the meaning of skip. Thank you. I will try the same thing with blockchain test.

**Comment by ulbqb** [comment]
- [x] PR to enable cancun and shanghai tests as bases
- [ ] [Skiped prague except 7702](https://github.com/Mdaiki0730/kaia/blob/feat/add-exec-test-blockchain/tests/block_test.go#L116-L120)
  - [ ] EIP2537 
  - [ ] EIP2935: @ulbqb 
  - [ ] EIP7623: @Mdaiki0730 
- [ ] PR to enable checking account storage
  - [ ] hogehoge
- [ ] old forks
- [ ] If there is a problem with 7702, it will be solved.

**Comment by ulbqb** [comment]
> EEST is the successor to [ethereum/tests](https://github.com/ethereum/tests) (aka "original tests")

https://github.com/ethereum/execution-spec-tests/pull/1165/files#diff-710a99e33d5a7edcaa8f1464a11316b463987558f100a960a496318389ab0b20
