### ISSUE TITLE
QA for v1.0.2

### ISSUE THREAD

**Issue by blukat29** [kaiachain/kaia#61]
- [x] Regular tests except sync test and load test @yoomee1313 https://github.com/kaiachain/kaia/issues/61#issuecomment-2282945035
- [x] PebbleDB support [#42](https://github.com/kaiachain/kaia/pull/42), [#56](https://github.com/kaiachain/kaia/pull/56) @hyeonLewis 
  - block sync without problem
  - leveldb-like metrics measured
  - RPC service without problem
- [x] kaia_getTotalSupply fixes [#58](https://github.com/kaiachain/kaia/pull/58) [#62](https://github.com/kaiachain/kaia/pull/62) [#65](https://github.com/kaiachain/kaia/pull/65) [#67](https://github.com/kaiachain/kaia/pull/67) [#68](https://github.com/kaiachain/kaia/pull/68) @ian0371 
  - The `showPartial` flag works as expected
  - Pruning EN falls back to Upstream Archive EN
  - Archive EN can serve any block
  - Correct result after `debug_setHead` or `--start-block-num` 
- [x] kaia_recoverFromTransaction fix [#71](https://github.com/kaiachain/kaia/pull/71) @ian0371 
  - Works with Eth tx types

**Comment by hyeonLewis** [comment]
PebbleDB support

- [ ] Block sync
  - Currently Pebble DB is syncing on mainnet in full node from genesis.
  - When node stopped abnormally, it can't get `td` from DB, which leads to nil point error. But easily recoverable by rewinding few blocks using `--start-block-num`.

- [ ] Metrics
  - Metrics are shown correctly. (EN0 for LevelDB, EN1 for PebbleDB)
<img width="2068" alt="Screenshot 2024-08-09 at 10 48 59" src="https://github.com/user-attachments/assets/29629037-f56e-47c5-84d8-d879bc3cb495">

- [ ] RPC serve

**Comment by yoomee1313** [comment]
Regular tests except sync test and load test
- [x] RPC/WS test: [KaiaTestReport.pdf](https://github.com/user-attachments/files/16576545/KaiaTestReport.pdf)
- [ ] governance/rolling update test:

**Comment by blukat29** [comment]
### kaia_recoverFromTransaction fix

```
function check(txhash) {
  console.log(kaia.getTransaction(txhash).type);
  console.log(kaia.getTransaction(txhash).from);
  console.log(kaia.recoverFromTransaction(eth.getRawTransaction(txhash), 'latest'))
}

// run on Kairos
check('0x7e3c5bdb4ee3974a6af2b50affa3f1d36d1ed56c3dd32f34287d8fbceca959c8') // type 0
check('0xb66a08753f0499f70165dce420a609dcf8e40fc801ecf4b1f3f3ef9c2deff55e') // type 2
check('0x17c667d2559c7477c5e568ce67e435eabf6eafc8511eee6166329ba89ea73363') // type 8
```

- v1.0.1
	```
	> check('0x7e3c5bdb4ee3974a6af2b50affa3f1d36d1ed56c3dd32f34287d8fbceca959c8') // type 0
	 TxTypeLegacyTransaction
	 0x7f0546832758f61410e81a94d7a07d55b1dfd278
	Error: should not be called by a legacy transaction
		at web3.js:6812:9(39)
		at send (web3.js:5223:62(29))
		at check (<eval>:4:42(28))
		at <eval>:1:6(2)
	
	> check('0xb66a08753f0499f70165dce420a609dcf8e40fc801ecf4b1f3f3ef9c2deff55e') // type 2
	 TxTypeEthereumDynamicFee
	 0x7f0546832758f61410e81a94d7a07d55b1dfd278
	Error: should not be called by a legacy transaction
		at web3.js:6812:9(39)
		at send (web3.js:5223:62(29))
		at check (<eval>:4:42(28))
		at <eval>:1:6(2)
	
	> check('0x17c667d2559c7477c5e568ce67e435eabf6eafc8511eee6166329ba89ea73363') // type 8
	 TxTypeValueTransfer
	 0x7f0546832758f61410e81a94d7a07d55b1dfd278
	 0x7f0546832758f61410e81a94d7a07d55b1dfd278
	```
- v1.0.2-rc.3
	```
	```
