### ISSUE TITLE
QA for v1.0.3

### ISSUE THREAD

**Issue by blukat29** [kaiachain/kaia#87]
- [x] Regular tests except sync test and load test @yoomee1313
- [x] Linux ARM64 distribution [#96](https://github.com/kaiachain/kaia/pull/96) [#100](https://github.com/kaiachain/kaia/pull/100) @blukat29  
- [x] OOM fix [#73](https://github.com/kaiachain/kaia/pull/73), [#74](https://github.com/kaiachain/kaia/pull/74) @ian0371 
- [x] Invalid block number argument fix [#76](https://github.com/kaiachain/kaia/pull/76), [#77](https://github.com/kaiachain/kaia/pull/77) @2dvorak 
- [x] SupplyManager missing block does not panic [#84](https://github.com/kaiachain/kaia/pull/84) @hyeonLewis 
- [x] Optional arguments to estimateGas APIs [#86](https://github.com/kaiachain/kaia/issues/86) @2dvorak 
- [x] Deprecated parameters in getParams and getChainConfig APIs [#92](https://github.com/kaiachain/kaia/issues/92) @hyunsooda 
- [x] Fix null dereference bug while loading snapshot [#102](https://github.com/kaiachain/kaia/pull/102) @yoomee1313

**Comment by hyunsooda** [comment]
- [x] Deprecated parameters in getParams and getChainConfig APIs [#92](https://github.com/kaiachain/kaia/issues/92) @hyunsooda 

<details> <summary> v.1.0.2 </summary>

```sh
> kaia.getChainConfig("latest")
{
  cancunCompatibleBlock: 0,
  chainId: 1000,
  deriveShaImpl: 0,
  ethTxTypeCompatibleBlock: 0,
  governance: {
    govParamContract: "0x0000000000000000000000000000000000000000",
    governanceMode: "none",
    governingNode: "0x0000000000000000000000000000000000000000",
    kip71: {
      basefeedenominator: 20,
      gastarget: 30000000,
      lowerboundbasefee: 25000000000,
      maxblockgasusedforbasefee: 60000000,
      upperboundbasefee: 750000000000
    },
    reward: {
      deferredTxFee: false,
      kip82ratio: "20/80",
      minimumStake: 2000000,
      mintingAmount: 0,
      proposerUpdateInterval: 3600,
      ratio: "100/0/0",
      stakingUpdateInterval: 86400,
      useGiniCoeff: false
    }
  },
  istanbul: {
    epoch: 604800,
    policy: 0,
    sub: 21
  },
  istanbulCompatibleBlock: 0,
  kaiaCompatibleBlock: 0,
  kip103CompatibleBlock: 0,
  kip103ContractAddress: "0x0000000000000000000000000000000000000000",
  kip160CompatibleBlock: 0,
  kip160ContractAddress: "0x0000000000000000000000000000000000000000",
  koreCompatibleBlock: 0,
  londonCompatibleBlock: 0,
  magmaCompatibleBlock: 0,
  randaoCompatibleBlock: 0,
  shanghaiCompatibleBlock: 0,
  unitPrice: 0
}
> kaia.getParams("latest")
{
  governance.deriveshaimpl: 0,
  governance.governancemode: "none",
  governance.governingnode: "0x0000000000000000000000000000000000000000",
  governance.govparamcontract: "0x0000000000000000000000000000000000000000",
  governance.unitprice: 0,
  istanbul.committeesize: 21,
  istanbul.epoch: 604800,
  istanbul.policy: 0,
  kip71.basefeedenominator: 20,
  kip71.gastarget: 30000000,
  kip71.lowerboundbasefee: 25000000000,
  kip71.maxblockgasusedforbasefee: 60000000,
  kip71.upperboundbasefee: 750000000000,
  reward.deferredtxfee: false,
  reward.kip82ratio: "20/80",
  reward.minimumstake: "2000000",
  reward.mintingamount: "0",
  reward.proposerupdateinterval: 3600,
  reward.ratio: "100/0/0",
  reward.stakingupdateinterval: 86400,
  reward.useginicoeff: false
}
```
</details>

<details> <summary> v.1.0.3rc </summary>

```sh
> kaia.getChainConfig("latest")
{
  cancunCompatibleBlock: 0,
  chainId: 1000,
  deriveShaImpl: 0,
  ethTxTypeCompatibleBlock: 0,
  governance: {
    govParamContract: "0x0000000000000000000000000000000000000000",
    governanceMode: "none",
    governingNode: "0x0000000000000000000000000000000000000000",
    kip71: {
      basefeedenominator: 20,
      gastarget: 30000000,
      lowerboundbasefee: 25000000000,
      maxblockgasusedforbasefee: 60000000,
      upperboundbasefee: 750000000000
    },
    reward: {
      deferredTxFee: false,
      kip82ratio: "20/80",
      minimumStake: 2000000,
      mintingAmount: 0,
      proposerUpdateInterval: 1,
      ratio: "100/0/0",
      stakingUpdateInterval: 1,
      useGiniCoeff: false
    }
  },
  istanbul: {
    epoch: 604800,
    policy: 0,
    sub: 21
  },
  istanbulCompatibleBlock: 0,
  kaiaCompatibleBlock: 0,
  kip103CompatibleBlock: 0,
  kip103ContractAddress: "0x0000000000000000000000000000000000000000",
  kip160CompatibleBlock: 0,
  kip160ContractAddress: "0x0000000000000000000000000000000000000000",
  koreCompatibleBlock: 0,
  londonCompatibleBlock: 0,
  magmaCompatibleBlock: 0,
  randaoCompatibleBlock: 0,
  shanghaiCompatibleBlock: 0,
  unitPrice: 0
}
> kaia.getParams("latest")
{
  governance.deriveshaimpl: 0,
  governance.governancemode: "none",
  governance.governingnode: "0x0000000000000000000000000000000000000000",
  governance.govparamcontract: "0x0000000000000000000000000000000000000000",
  governance.unitprice: 0,
  istanbul.committeesize: 21,
  istanbul.epoch: 604800,
  istanbul.policy: 0,
  kip71.basefeedenominator: 20,
  kip71.gastarget: 30000000,
  kip71.lowerboundbasefee: 25000000000,
  kip71.maxblockgasusedforbasefee: 60000000,
  kip71.upperboundbasefee: 750000000000,
  reward.deferredtxfee: false,
  reward.kip82ratio: "20/80",
  reward.minimumstake: "2000000",
  reward.mintingamount: "0",
  reward.proposerupdateinterval: 1,
  reward.ratio: "100/0/0",
  reward.stakingupdateinterval: 1,
  reward.useginicoeff: false
}
```

**Comment by hyeonLewis** [comment]
SupplyManager missing block does not panic

- Setup
  - `homi setup --cn-num 4 --baobab --gen-type local`
  - Stop one CN
  - Restart above CN

- Delete block, header, receipt
  - In `accumulateReward()`, add a logic to delete block/header/receipt of middle block when big catchup
  - <details> <summary> Delete code (when testing missing block) </summary>

    ```
    if to > from+5 {
	    targetBlockNum := (from + to) / 2
	    targetBlock := sm.chain.GetBlockByNumber(targetBlockNum)
    
	    logger.Info("[QA] Deleting block", "number", targetBlockNum, "hash", targetBlock.Hash())
            
	    sm.db.DeleteBlock(targetBlock.Hash(), targetBlockNum)
	    // sm.db.DeleteHeader(targetBlock.Hash(), targetBlockNum)
	    // sm.db.DeleteReceipts(targetBlock.Hash(), targetBlockNum)
    }
    ```
    </details>

- v1.0.2
  - [x] Panic for missing block
  - [x] Panic for missing header
  - [ ] Panic for missing receipt
    - It doesn't panic since there's branch for nil receipt

- v1.0.3-rc.1
  - [x] Accumulation failed at missing block
  - [x] Accumulation failed at missing header
  - [x] Accumulation failed at missing receipt

<details> <summary> v1.0.2 </summary>

```
// For missing block
INFO[09/23,11:15:53 +09] [44|reward/supply_manager.go:315]              Total supply big step catchup             last=0 head=28 minted=400000000000000000000000000000000000000000000000000 burntFee=0
INFO[09/23,11:15:53 +09] [44|reward/supply_manager.go:410]              [QA] Deleting block                       number=14 hash=d3c945…49babd
INFO[09/23,11:15:53 +09] [40|node/node.go:409]                          IPC endpoint opened                       url=/Users/lewiskim/Kaia/homi-local/output/cn2/data/klay.ipc
INFO[09/23,11:15:53 +09] [40|node/node.go:463]                          HTTP endpoint opened                      url=http://127.0.0.1:8552/                                    cors= vhosts=*
INFO[09/23,11:15:53 +09] [51|work/work.go:159]                          Starting mining operation
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10530c174]

goroutine 253 [running]:
github.com/kaiachain/kaia/blockchain/types.(*Block).Hash(0x14010d05f00?)
	/Users/lewiskim/Kaia/kaia/blockchain/types/block.go:382 +0x24
github.com/kaiachain/kaia/reward.(*supplyManager).accumulateReward(0x140001de480, 0x0, 0x1c, 0x14001248080?, 0x1)
	/Users/lewiskim/Kaia/kaia/reward/supply_manager.go:427 +0x234
github.com/kaiachain/kaia/reward.(*supplyManager).catchup(0x140001de480)
	/Users/lewiskim/Kaia/kaia/reward/supply_manager.go:317 +0x6a8
created by github.com/kaiachain/kaia/reward.(*supplyManager).Start in goroutine 1
	/Users/lewiskim/Kaia/kaia/reward/supply_manager.go:125 +0x70
```

```
// For missing header
INFO[09/23,11:18:05 +09] [44|reward/supply_manager.go:315]              Total supply big step catchup             last=0 head=8 minted=400000000000000000000000000000000000000000000000000 burntFee=0
INFO[09/23,11:18:05 +09] [44|reward/supply_manager.go:410]              [QA] Deleting block                       number=4 hash=bdb232…e9332c
INFO[09/23,11:18:05 +09] [40|node/node.go:409]                          IPC endpoint opened                       url=/Users/lewiskim/Kaia/homi-local/output/cn2/data/klay.ipc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1a8 pc=0x103667ae8]

goroutine 253 [running]:
github.com/kaiachain/kaia/reward.GetTotalTxFee(0x0, {0x106ded4c0, 0x0, 0x1400168a7c0?}, {0x0, 0x0, 0x140006be990?}, {0x14010cc24c0, 0x1, 0x1, ...}, ...)
	/Users/lewiskim/Kaia/kaia/reward/reward_distributor.go:183 +0x48
github.com/kaiachain/kaia/reward.NewRewardConfig(0x0, {0x106ded4c0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x14010cc24c0, 0x1, 0x1, ...}, ...)
	/Users/lewiskim/Kaia/kaia/reward/reward_distributor.go:162 +0x110
github.com/kaiachain/kaia/reward.GetTotalReward(0x0, {0x106ded4c0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x14010cc24c0, 0x1, 0x1, ...}, ...)
	/Users/lewiskim/Kaia/kaia/reward/reward_distributor.go:225 +0x7c
github.com/kaiachain/kaia/reward.(*supplyManager).accumulateReward(0x14001492700, 0x0, 0x8, 0x1400979e880?, 0x1)
	/Users/lewiskim/Kaia/kaia/reward/supply_manager.go:434 +0x358
github.com/kaiachain/kaia/reward.(*supplyManager).catchup(0x14001492700)
	/Users/lewiskim/Kaia/kaia/reward/supply_manager.go:317 +0x6a8
created by github.com/kaiachain/kaia/reward.(*supplyManager).Start in goroutine 1
	/Users/lewiskim/Kaia/kaia/reward/supply_manager.go:125 +0x70
```

</details>


<details> <summary> v1.0.3-rc.1</summary>

```
// For missing block & header
INFO[09/23,10:57:29 +09] [44|reward/supply_manager.go:315]              Total supply big step catchup             last=0 head=15 minted=400000000000000000000000000000000000000000000000000 burntFee=0
INFO[09/23,10:57:29 +09] [44|reward/supply_manager.go:410]              [QA] Deleting block                       number=7  hash=8d667a…0874c8
INFO[09/23,10:57:29 +09] [40|node/node.go:409]                          IPC endpoint opened                       url=/Users/lewiskim/Kaia/homi-local/output/cn2/data/klay.ipc
INFO[09/23,10:57:29 +09] [40|node/node.go:463]                          HTTP endpoint opened                      url=http://127.0.0.1:8552/                                    cors= vhosts=*
INFO[09/23,10:57:29 +09] [51|work/work.go:159]                          Starting mining operation
ERROR[09/23,10:57:29 +09] [44|reward/supply_manager.go:430]              Header not found                          number=7
ERROR[09/23,10:57:29 +09] [44|reward/supply_manager.go:320]              Total supply accumulate failed            from=0 to=15 err="block not found"
```

```
// For missing receipt
INFO[09/23,11:07:43 +09] [44|reward/supply_manager.go:315]              Total supply big step catchup             last=0 head=15 minted=400000000000000000000000000000000000000000000000000 burntFee=0
INFO[09/23,11:07:43 +09] [44|reward/supply_manager.go:410]              [QA] Deleting block                       number=7  hash=8383be…8952e6
INFO[09/23,11:07:43 +09] [40|node/node.go:463]                          HTTP endpoint opened                      url=http://127.0.0.1:8552/                                    cors= vhosts=*
INFO[09/23,11:07:43 +09] [51|work/work.go:159]                          Starting mining operation
INFO[09/23,11:07:43 +09] [51|work/worker.go:524]                        Mining start for new block is later than expected  nextBlockNum=16 delay=1m2.255815s parentBlockTimestamp=1727057200 nextBlockTimestamp=1727057263
ERROR[09/23,11:07:43 +09] [44|reward/supply_manager.go:440]              Receipts not found                        number=7
ERROR[09/23,11:07:43 +09] [44|reward/supply_manager.go:320]              Total supply accumulate failed            from=0 to=15 err="block not found"
```

```
// API response
> kaia.getTotalSupply("latest")
Error: block not found
	at web3.js:6814:9(39)
	at send (web3.js:5225:62(29))
	at <eval>:1:20(3)

// after checkpoint interval (128 blocks)
> kaia.getTotalSupply("latest")
Error: no supply checkpoint found
	at web3.js:6814:9(39)
	at send (web3.js:5225:62(29))
	at <eval>:1:20(3)
```
</details>

**Comment by 2dvorak** [comment]
**Invalid block number argument fix**
1. #76 sanitize inputBlockNumberFormatter
   - [x] input blocknumber sanitized

<details><summary>v1.0.2</summary>

```
klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "latest2")
Error: the header does not exist (block number: 30506450030916658)
        at web3.js:6812:9(39)
        at send (web3.js:5223:62(29))
        at <eval>:1:13(4)

> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "www")
Error: the header does not exist (block number: 7829367)
        at web3.js:6812:9(39)
        at send (web3.js:5223:62(29))
        at <eval>:1:13(4)

> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "wwwwwwwwwwwwwwwwwww")
Error: invalid argument 1: hex number > 64 bits
        at web3.js:6812:9(39)
        at send (web3.js:5223:62(29))
        at <eval>:1:13(4)
```
</details>

<details><summary>v1.0.3-rc.1</summary>

```
 klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "latest2")
Error: input block number(latest2) is invalid
        at inputBlockNumberFormatter (web3.js:3854:11(37))
        at inputDefaultBlockNumberFormatter (web3.js:3843:37(11))
        at web3.js:5169:37(8)
        at map (native)
        at web3.js:5168:35(12)
        at web3.js:5194:34(15)
        at send (web3.js:5219:39(11))
        at <eval>:1:13(4)

> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "www")
Error: input block number(www) is invalid
        at inputBlockNumberFormatter (web3.js:3854:11(37))
        at inputDefaultBlockNumberFormatter (web3.js:3843:37(11))
        at web3.js:5169:37(8)
        at map (native)
        at web3.js:5168:35(12)
        at web3.js:5194:34(15)
        at send (web3.js:5219:39(11))
        at <eval>:1:13(4)

> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "wwwwwwwwwwwwwwwwwww")
Error: input block number(wwwwwwwwwwwwwwwwwww) is invalid
        at inputBlockNumberFormatter (web3.js:3854:11(37))
        at inputDefaultBlockNumberFormatter (web3.js:3843:37(11))
        at web3.js:5169:37(8)
        at map (native)
        at web3.js:5168:35(12)
        at web3.js:5194:34(15)
        at send (web3.js:5219:39(11))
        at <eval>:1:13(4)

> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", "0x1")
"0x"
> klay.getCode("0x98f4aB2c97eFff367827777e2fd96c536f38df1d", 0x1)
"0x"
```
</details>


2. #77 handle unknown blocknumber in getStakingInfo and getRewards
   - [x] future blocknumber and "pending" allowed

<details><summary>v1.0.2</summary>

```
 kaia.getRewards(99999999)
Error: method handler crashed
        at web3.js:6812:9(39)
        at send (web3.js:5223:62(29))
        at <eval>:1:16(3)

> kaia.getRewards("pending")
Error: method handler crashed
        at web3.js:6812:9(39)
        at send (web3.js:5223:62(29))
        at <eval>:1:16(3)

> kaia.getStakingInfo(99999999)
Error: method handler crashed
        at web3.js:6812:9(39)
        at send (web3.js:5223:62(29))
        at <eval>:1:20(3)
```
</details>

<details><summary>v1.0.3-rc.1</summary>

```
> kaia.getRewards(99999999)
Error: Unknown block
        at web3.js:6814:9(39)
        at send (web3.js:5225:62(29))
        at <eval>:1:16(3)

> kaia.getRewards("pending")
{
  burntFee: 0,
  kef: 0,
  kif: 0,
  minted: 0,
  proposer: 0,
  rewards: {
    0x0a41008428694117e507477959ef8212255d0cfe: 0
  },
  stakers: 0,
  totalFee: 0
}
> kaia.getStakingInfo(99999999)
Error: Unknown block
        at web3.js:6814:9(39)
        at send (web3.js:5225:62(29))
        at <eval>:1:20(3)
```
</details>

**Optional arguments to estimateGas APIs**
TBU

**Comment by ian0371** [comment]
- [ ] OOM fix

<details>

<summary>v1.0.2</summary>
https://github.com/kaiachain/kaia/issues/75

<summary>v1.0.3-rc.1</summary>
<img width="1831" alt="image" src="https://github.com/user-attachments/assets/6d50b47b-adc0-48cc-9cfc-2dedd48ce5e9">

</details>

**Comment by blukat29** [comment]
### Linux ARM64 distribution

- Environment
	- AWS c6g.medium
	```
	$ uname -mor
	6.1.109-118.189.amzn2023.aarch64 aarch64 GNU/Linux
	```
- RPM successfully installs and runs
	```
	$ wget https://packages.kaia.io/kaia/v1.0.3~rc.2/kend-v1.0.3~rc.2-0.el7.aarch64.rpm
	$ sudo yum install ./kend-v1.0.3~rc.2-0.el7.aarch64.rpm
	$ sudo systemctl start kend
	$ sudo tail -f /var/log/kend/kend.out
	$ file /usr/bin/ken
	/usr/bin/ken: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, Go BuildID=RQtw6JvYcqfeA3LkHAOH/P025tBzhU57cCsi2k8uk/lZmLvKCKgd7PHxVxMB-6/6RCL-1L7bSiAKX9UMoW7, BuildID[sha1]=1512656651a3bde79b8ce6aa667d398ed9bc5124, stripped
	$ /usr/bin/ken version
	Kaia v1.0.3
	```
- TGZ successfully runs
	```
	$ wget https://packages.kaia.io/kaia/v1.0.3~rc.2/ken-v1.0.3~rc.2-0-linux-arm64.tar.gz
	$ tar xf ken-v1.0.3~rc.2-0-linux-arm64.tar.gz
	$ file ./ken-linux-arm64/bin/ken
	./ken-linux-arm64/bin/ken: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=a5832e90e93153654ff2cf6b39cf47b2eeaf53ec, for GNU/Linux 3.7.0, with debug_info, not stripped
	$ ./ken-linux-arm64/bin/ken version
	Kaia v1.0.3~rc.2+5e32e8f131
	```

**Comment by yoomee1313** [comment]
## Regular Test
[x] rpc/ws test: [KaiaTestReport.pdf](https://github.com/user-attachments/files/17124661/KaiaTestReport.pdf)
[ ] governance test: 
[x] rolling update test: [rolling_update_result.log](https://github.com/user-attachments/files/17124662/rolling_update_result.log)

**Comment by yoomee1313** [comment]
### Fix null dereference bug while loading snapshot
* check if restart at latest block doesn't panic: restarted the full en node at 165313436 with v1.0.2. But it didn't panic.
* handler crash
<details>

<summary>v1.0.2 - getCouncil crashed </summary>
ERROR[09/25,20:21:12 +09] [26] Proposer is not available now.            proposer address=0x993efC86499FF9a47E5770040a02F37ed9469911
ERROR[09/25,20:21:12 +09] [39] RPC method kaia_getCouncil crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 434555796 [running]:
github.com/kaiachain/kaia/networks/rpc.(*callback).call.func1()
        /home/ubuntu/kaia/networks/rpc/service.go:225 +0x85
panic({0x1ee0f00?, 0x4c7d340?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/kaiachain/kaia/consensus/istanbul/validator.RecoverWeightedCouncilProposer({0x3a62340?, 0xc0ae32f680}, {0xc05082f900?, 0x22, 0x2d?})
        /home/ubuntu/kaia/consensus/istanbul/validator/weighted.go:138 +0x2a1
github.com/kaiachain/kaia/consensus/istanbul/backend.(*Snapshot).UnmarshalJSON(0xc0efb7a400, {0xc0d4b25980, 0x188b, 0x1980})
        /home/ubuntu/kaia/consensus/istanbul/backend/snapshot.go:378 +0x28b
encoding/json.(*decodeState).object(0xc0835c3050, {0x20bf000?, 0xc0efb7a400?, 0x7fc41ef8f8a8?})
        /usr/local/go/src/encoding/json/decode.go:604 +0x6d0
encoding/json.(*decodeState).value(0xc0835c3050, {0x20bf000?, 0xc0efb7a400?, 0xc04b02a008?})
        /usr/local/go/src/encoding/json/decode.go:374 +0x3e
encoding/json.(*decodeState).unmarshal(0xc0835c3050, {0x20bf000?, 0xc0efb7a400?})
        /usr/local/go/src/encoding/json/decode.go:181 +0x11e
encoding/json.Unmarshal({0xc0d4b25980, 0x188b, 0x1980}, {0x20bf000, 0xc0efb7a400})
        /usr/local/go/src/encoding/json/decode.go:108 +0xf9
github.com/kaiachain/kaia/consensus/istanbul/backend.loadSnapshot({0x3a7e990?, 0xc0004c40a0?}, {0x26, 0xd, 0xfb, 0x91, 0x82, 0x59, 0x9e, 0x61, ...})
        /home/ubuntu/kaia/consensus/istanbul/backend/snapshot.go:99 +0x88
github.com/kaiachain/kaia/consensus/istanbul/backend.(*backend).prepareSnapshotApply(0xc0001a5380, {0x3a508e8, 0xc02336a008}, 0x20e5be0?, {0x26, 0xd, 0xfb, 0x91, 0x82, 0x59, ...}, ...)
        /home/ubuntu/kaia/consensus/istanbul/backend/engine.go:905 +0x11c
github.com/kaiachain/kaia/consensus/istanbul/backend.(*backend).GetKaiaHeadersForSnapshotApply(0xc0038c5418?, {0x3a508e8, 0xc02336a008}, 0xd2436ac2453ee1c6?, {0x26, 0xd, 0xfb, 0x91, 0x82, 0x59, ...}, ...)
        /home/ubuntu/kaia/consensus/istanbul/backend/engine.go:938 +0x50
github.com/kaiachain/kaia/consensus/istanbul/backend.checkStatesForSnapshot({0x3a508e8, 0xc02336a008}, 0x2?, 0x2?, {0x26, 0xd, 0xfb, 0x91, 0x82, 0x59, ...})
        /home/ubuntu/kaia/consensus/istanbul/backend/api.go:597 +0x5f
github.com/kaiachain/kaia/consensus/istanbul/backend.checkStatesAndGetSnapshot({0x3a508e8, 0xc02336a008}, 0xc0001a5380, 0x9d96c00, {0x26, 0xd, 0xfb, 0x91, 0x82, 0x59, ...})
        /home/ubuntu/kaia/consensus/istanbul/backend/api.go:612 +0x4d
github.com/kaiachain/kaia/consensus/istanbul/backend.(*APIExtension).GetCouncil(0xc02ab116f8, 0x497593?)
        /home/ubuntu/kaia/consensus/istanbul/backend/api.go:235 +0xf2
reflect.Value.call({0xc02ac574a0?, 0xc02adc2428?, 0x50?}, {0x21e7359, 0x4}, {0xc00b8c54a0, 0x2, 0xc00b8c54a0?})
        /usr/local/go/src/reflect/value.go:596 +0xca6
reflect.Value.Call({0xc02ac574a0?, 0xc02adc2428?, 0x0?}, {0xc00b8c54a0?, 0x1?, 0xc00cf93cc0?})
        /usr/local/go/src/reflect/value.go:380 +0xb9
github.com/kaiachain/kaia/networks/rpc.(*callback).call(0xc02adcd740, {0x3a430a0, 0xc00b8c5400}, {0xc033587bc0, 0xf}, {0xc057b4d6b0, 0x1, 0xc033587bc5?})
        /home/ubuntu/kaia/networks/rpc/service.go:231 +0x36d
github.com/kaiachain/kaia/networks/rpc.(*handler).runMethod(0xc033587be0?, {0x3a430a0, 0xc00b8c5400}, 0xc0d859db90, 0x1?, {0xc057b4d6b0, 0x1, 0x1})
        /home/ubuntu/kaia/networks/rpc/handler.go:432 +0x55
github.com/kaiachain/kaia/networks/rpc.(*handler).handleCall(0xc0efb7a300, 0xc0717bf1d0, 0xc0d859db90)
        /home/ubuntu/kaia/networks/rpc/handler.go:380 +0x21e
github.com/kaiachain/kaia/networks/rpc.(*handler).handleCallMsg(0xc0efb7a300, 0xc0717bf1d0, 0xc0d859db90)
        /home/ubuntu/kaia/networks/rpc/handler.go:337 +0xbd
github.com/kaiachain/kaia/networks/rpc.(*handler).handleMsg.func2(0xc0717bf1d0)
        /home/ubuntu/kaia/networks/rpc/handler.go:169 +0x2f
github.com/kaiachain/kaia/networks/rpc.(*handler).startCallProc.func1()
        /home/ubuntu/kaia/networks/rpc/handler.go:259 +0xec
created by github.com/kaiachain/kaia/networks/rpc.(*handler).startCallProc in goroutine 434555794
        /home/ubuntu/kaia/networks/rpc/handler.go:254 +0xb3
</details>

<details>

<summary>v1.0.3-rc.3 - getCouncil doesn't crashed </summary>

</details>

* node crash
  * v1.0.2 - archive en node crashed when restart near 165243904
  * v1.0.3-rc.3 - archive en node doesn't crashed when restart near 165243904
